# Generated by Django 5.0.3 on 2025-11-05 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_clerk_user_id'),
    ]

    operations = [
        # This migration is intentionally left empty because the clerk_user_id field
        # was already added in migration 0004_document_clerk_user_id
        # This fixes the duplicate column error when migrating to PostgreSQL
    ]