# Generated by Django 5.0.3 on 2025-11-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_clerk_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='clerk_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]